- name: Docker
  type: docker
  id: docker
  icon: docker.png
  subitems:
    - name: Images
      type: docker-image-list
      id: docker-image-list
      icon: docker.png
      subitems: []
      raw: {}
    - name: Containers
      type: docker-container-list
      id: docker-container-list
      icon: docker.svg
      subitems: []
      raw: {}
    - name: Registries
      type: docker-registry-list
      id: docker-registry-list
      icon: docker.svg
      subitems: []
      raw: {}
  raw: {}
  